import type { ConsoleDataSet } from '../types/console';

export const mockConsoleData: ConsoleDataSet = {
  summary: {
    resourceCount: 6,
    snapshotCount: 5,
    eventCount: 8,
    successCount: 1842,
    failureCount: 17,
    rejectedCount: 36,
    cancelledCount: 4,
    fallbackCount: 9,
    retryStoppedCount: 7,
    blockedCount: 5,
    isolatedCount: 3,
    sentinelResourceCount: 2,
    instanceSuspectCount: 1,
    quarantineCandidateCount: 1,
    recoveryProbeCount: 0,
    faultTraceCount: 4,
    stoppedTraceCount: 3,
    trafficClassCounts: {
      online: 3,
      batch: 1,
      ONLINE: 3,
      BATCH: 2,
    },
    priorityCounts: {
      normal: 2,
      high: 1,
      low: 1,
      NORMAL: 3,
      HIGH: 1,
      LOW: 2,
    },
    openCircuitCount: 1,
    halfOpenCircuitCount: 1,
    degradedResourceCount: 1,
    lastEventAt: '2026-06-24T01:28:12Z',
  },
  resources: [
    {
      resourceKey: 'cache:redis:user-profile:get',
      kind: 'CACHE',
      name: 'user-profile',
      provider: 'redis',
      operation: 'get',
      trafficClass: 'online',
      priority: 'normal',
      policySnapshot: {
        maxRequestsPerWindow: 500,
        rateLimitWindow: 'PT1S',
        maxConcurrency: 64,
        degraded: false,
        minimumRequests: 20,
        failureRateThreshold: 50,
        slowCallThreshold: 60,
        slowCallDuration: 'PT0.2S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 2,
        slidingWindowSize: 100,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 8,
      },
      runtimeSnapshot: {
        resourceKey: 'cache:redis:user-profile:get',
        trafficClass: 'online',
        priority: 'normal',
        circuitState: 'CLOSED',
        windowCalls: 96,
        windowFailures: 1,
        windowSlowCalls: 3,
        consecutiveFailures: 0,
        totalRejections: 2,
        lastRejectionReason: 'NONE',
        lastIsolationReason: 'NONE',
        lastCancellationReason: 'NONE',
        lastRetryStopReason: 'NONE',
        openUntil: null,
        activeConcurrency: 3,
        maxConcurrency: 64,
        maxRequestsPerWindow: 500,
        rateLimitWindow: 'PT1S',
        degraded: false,
        minimumRequests: 20,
        failureRateThreshold: 50,
        slowCallThreshold: 60,
        slowCallDuration: 'PT0.2S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 2,
        slidingWindowSize: 100,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 8,
        lastStateTransitionAt: '2026-06-24T01:20:02Z',
        lastOutcome: 'SUCCESS',
        lastOutcomeAt: '2026-06-24T01:28:12Z',
      },
      instanceHealthSnapshots: [
        {
          resourceKey: 'cache:redis:user-profile:get',
          serviceKey: 'profile-service',
          instanceKey: 'instance-a',
          zone: 'zone-a',
          state: 'HEALTHY',
          quarantineReason: 'NONE',
          recoveryAdvice: 'NONE',
          windowCalls: 24,
          failureCount: 0,
          slowCallCount: 1,
          timeoutCount: 0,
          resetCount: 0,
          serverErrorCount: 0,
          failureRatio: 0,
          slowRatio: 0.04,
          timeoutRatio: 0,
          skewFactor: 0,
          lastSignalAt: '2026-06-24T01:28:12Z',
          lastChangedAt: null,
        },
        {
          resourceKey: 'cache:redis:user-profile:get',
          serviceKey: 'profile-service',
          instanceKey: 'instance-c',
          zone: 'zone-a',
          state: 'QUARANTINE_CANDIDATE',
          quarantineReason: 'SERVER_ERROR_RATIO',
          recoveryAdvice: 'QUARANTINE_CANDIDATE',
          windowCalls: 24,
          failureCount: 18,
          slowCallCount: 3,
          timeoutCount: 0,
          resetCount: 0,
          serverErrorCount: 18,
          failureRatio: 0.75,
          slowRatio: 0.13,
          timeoutRatio: 0,
          skewFactor: 9,
          lastSignalAt: '2026-06-24T01:28:10Z',
          lastChangedAt: '2026-06-24T01:27:54Z',
        },
      ],
      lastTraceOutcome: 'NONE',
      lastTraceStopReason: 'INSTANCE_QUARANTINE_CANDIDATE',
    },
    {
      resourceKey: 'messaging:kafka:orders:send',
      kind: 'MESSAGING',
      name: 'orders',
      provider: 'kafka',
      operation: 'send',
      trafficClass: 'online',
      priority: 'normal',
      policySnapshot: {
        maxRequestsPerWindow: 120,
        rateLimitWindow: 'PT1S',
        maxConcurrency: 24,
        degraded: false,
        minimumRequests: 12,
        failureRateThreshold: 40,
        slowCallThreshold: 50,
        slowCallDuration: 'PT1S',
        openStateDuration: 'PT45S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 80,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 4,
      },
      runtimeSnapshot: {
        resourceKey: 'messaging:kafka:orders:send',
        trafficClass: 'online',
        priority: 'normal',
        circuitState: 'OPEN',
        windowCalls: 32,
        windowFailures: 15,
        windowSlowCalls: 11,
        consecutiveFailures: 5,
        totalRejections: 28,
        lastRejectionReason: 'CIRCUIT_OPEN',
        lastIsolationReason: 'PRIORITY_CIRCUIT_OPEN',
        lastCancellationReason: 'CLIENT_DISCONNECTED',
        openUntil: '2026-06-24T01:29:00Z',
        activeConcurrency: 0,
        maxConcurrency: 24,
        maxRequestsPerWindow: 120,
        rateLimitWindow: 'PT1S',
        degraded: false,
        minimumRequests: 12,
        failureRateThreshold: 40,
        slowCallThreshold: 50,
        slowCallDuration: 'PT1S',
        openStateDuration: 'PT45S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 80,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 4,
        lastStateTransitionAt: '2026-06-24T01:28:15Z',
        lastOutcome: 'REJECTED',
        lastOutcomeAt: '2026-06-24T01:28:17Z',
      },
      lastTraceOutcome: 'REJECTED',
      lastTraceStopReason: 'BLOCKED',
    },
    {
      resourceKey: 'job:scheduler:billing-close:run',
      kind: 'JOB',
      name: 'billing-close',
      provider: 'scheduler',
      operation: 'run',
      trafficClass: 'online',
      priority: 'high',
      policySnapshot: {
        maxRequestsPerWindow: 8,
        rateLimitWindow: 'PT1M',
        maxConcurrency: 1,
        degraded: false,
        minimumRequests: 5,
        failureRateThreshold: 50,
        slowCallThreshold: null,
        slowCallDuration: null,
        openStateDuration: 'PT60S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 20,
        slidingWindowDuration: 'PT5M',
        consecutiveFailureThreshold: 3,
      },
      runtimeSnapshot: {
        resourceKey: 'job:scheduler:billing-close:run',
        trafficClass: 'online',
        priority: 'high',
        circuitState: 'HALF_OPEN',
        windowCalls: 9,
        windowFailures: 3,
        windowSlowCalls: 0,
        consecutiveFailures: 0,
        totalRejections: 4,
        lastRejectionReason: 'HALF_OPEN_LIMITED',
        lastIsolationReason: 'NONE',
        lastCancellationReason: 'NONE',
        openUntil: null,
        activeConcurrency: 1,
        maxConcurrency: 1,
        maxRequestsPerWindow: 8,
        rateLimitWindow: 'PT1M',
        degraded: false,
        minimumRequests: 5,
        failureRateThreshold: 50,
        slowCallThreshold: null,
        slowCallDuration: null,
        openStateDuration: 'PT60S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 20,
        slidingWindowDuration: 'PT5M',
        consecutiveFailureThreshold: 3,
        lastStateTransitionAt: '2026-06-24T01:27:30Z',
        lastOutcome: 'SUCCESS',
        lastOutcomeAt: '2026-06-24T01:28:01Z',
      },
      lastTraceOutcome: 'SUCCESS',
      lastTraceStopReason: 'NONE',
    },
    {
      resourceKey: 'governance:nexary:default:execute',
      kind: 'GOVERNANCE',
      name: 'default',
      provider: 'nexary',
      operation: 'execute',
      trafficClass: 'batch',
      priority: 'normal',
      policySnapshot: {
        maxRequestsPerWindow: 200,
        rateLimitWindow: 'PT1S',
        maxConcurrency: 32,
        degraded: true,
        minimumRequests: 10,
        failureRateThreshold: 50,
        slowCallThreshold: 50,
        slowCallDuration: 'PT0.5S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 50,
        slidingWindowDuration: 'PT30S',
        consecutiveFailureThreshold: 5,
      },
      runtimeSnapshot: {
        resourceKey: 'governance:nexary:default:execute',
        trafficClass: 'batch',
        priority: 'normal',
        circuitState: 'CLOSED',
        windowCalls: 20,
        windowFailures: 0,
        windowSlowCalls: 0,
        consecutiveFailures: 0,
        totalRejections: 2,
        lastRejectionReason: 'DEGRADED',
        lastIsolationReason: 'PRIORITY_DEGRADED',
        lastCancellationReason: 'NONE',
        openUntil: null,
        activeConcurrency: 0,
        maxConcurrency: 32,
        maxRequestsPerWindow: 200,
        rateLimitWindow: 'PT1S',
        degraded: true,
        minimumRequests: 10,
        failureRateThreshold: 50,
        slowCallThreshold: 50,
        slowCallDuration: 'PT0.5S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 50,
        slidingWindowDuration: 'PT30S',
        consecutiveFailureThreshold: 5,
        lastStateTransitionAt: '2026-06-24T01:10:00Z',
        lastOutcome: 'REJECTED',
        lastOutcomeAt: '2026-06-24T01:25:19Z',
      },
      lastTraceOutcome: 'ISOLATED',
      lastTraceStopReason: 'ISOLATED',
    },
  ],
  events: [
    {
      resourceKey: 'cache:redis:user-profile:get',
      trafficClass: 'ONLINE',
      priority: 'NORMAL',
      action: 'QUARANTINE_CANDIDATE',
      outcome: 'NONE',
      rejectionReason: 'NONE',
      isolationReason: 'NONE',
      blockReason: 'NONE',
      cancellationReason: 'NONE',
      retryStopReason: 'NONE',
      instanceHealthState: 'QUARANTINE_CANDIDATE',
      quarantineReason: 'SERVER_ERROR_RATIO',
      recoveryAdvice: 'QUARANTINE_CANDIDATE',
      traceStage: 'INSTANCE_HEALTH',
      tracePrimaryStopReason: 'INSTANCE_QUARANTINE_CANDIDATE',
      circuitState: 'CLOSED',
      timestamp: '2026-06-24T01:28:19Z',
      durationBucket: 'NOT_RUN',
    },
    {
      resourceKey: 'messaging:kafka:orders:send',
      trafficClass: 'ONLINE',
      priority: 'NORMAL',
      action: 'REJECT',
      outcome: 'REJECTED',
      rejectionReason: 'CIRCUIT_OPEN',
      isolationReason: 'PRIORITY_CIRCUIT_OPEN',
      blockReason: 'CIRCUIT_OPEN',
      cancellationReason: 'NONE',
      retryStopReason: 'CIRCUIT_OPEN',
      traceStage: 'GOVERNANCE',
      tracePrimaryStopReason: 'BLOCKED',
      circuitState: 'OPEN',
      timestamp: '2026-06-24T01:28:17Z',
      durationBucket: 'NOT_RUN',
    },
    {
      resourceKey: 'cache:redis:user-profile:get',
      trafficClass: 'ONLINE',
      priority: 'NORMAL',
      action: 'EXECUTE',
      outcome: 'SUCCESS',
      rejectionReason: 'NONE',
      isolationReason: 'NONE',
      cancellationReason: 'NONE',
      retryStopReason: 'NONE',
      traceStage: 'CACHE',
      tracePrimaryStopReason: 'NONE',
      circuitState: 'CLOSED',
      timestamp: '2026-06-24T01:28:12Z',
      durationBucket: 'LT_10_MS',
    },
    {
      resourceKey: 'job:scheduler:billing-close:run',
      trafficClass: 'ONLINE',
      priority: 'HIGH',
      action: 'EXECUTE',
      outcome: 'SUCCESS',
      rejectionReason: 'NONE',
      isolationReason: 'NONE',
      cancellationReason: 'NONE',
      retryStopReason: 'NONE',
      traceStage: 'JOB',
      tracePrimaryStopReason: 'NONE',
      circuitState: 'HALF_OPEN',
      timestamp: '2026-06-24T01:28:01Z',
      durationBucket: 'LT_100_MS',
    },
    {
      resourceKey: 'governance:nexary:default:execute',
      trafficClass: 'BATCH',
      priority: 'LOW',
      action: 'FALLBACK',
      outcome: 'ISOLATED',
      rejectionReason: 'DEGRADED',
      isolationReason: 'PRIORITY_DEGRADED',
      cancellationReason: 'NONE',
      retryStopReason: 'DEGRADED',
      traceStage: 'GOVERNANCE',
      tracePrimaryStopReason: 'ISOLATED',
      circuitState: 'CLOSED',
      timestamp: '2026-06-24T01:25:19Z',
      durationBucket: 'NOT_RUN',
    },
    {
      resourceKey: 'messaging:kafka:orders:send',
      trafficClass: 'ONLINE',
      priority: 'NORMAL',
      action: 'CANCEL',
      outcome: 'CANCELLED',
      rejectionReason: 'NONE',
      isolationReason: 'NONE',
      cancellationReason: 'CLIENT_DISCONNECTED',
      retryStopReason: 'CLIENT_DISCONNECTED',
      traceStage: 'REQUEST',
      tracePrimaryStopReason: 'CANCELLED',
      circuitState: 'OPEN',
      timestamp: '2026-06-24T01:25:10Z',
      durationBucket: 'NOT_RUN',
    },
  ],
  traces: [
    {
      traceKey: 'trace-4',
      rootResourceKey: 'cache:redis:user-profile:get',
      startedAt: '2026-06-24T01:28:18Z',
      lastEventAt: '2026-06-24T01:28:19Z',
      terminalOutcome: 'NONE',
      primaryStopReason: 'INSTANCE_QUARANTINE_CANDIDATE',
      suggestedResourceKey: 'cache:redis:user-profile:get',
      steps: [
        {
          stage: 'DOWNSTREAM',
          resourceKey: 'cache:redis:user-profile:get',
          action: 'EXECUTE',
          outcome: 'FAILURE',
          durationBucket: 'LT_500_MS',
          timestamp: '2026-06-24T01:28:18Z',
          rejectionReason: 'NONE',
          blockReason: 'NONE',
          cancellationReason: 'NONE',
          retryStopReason: 'NONE',
          isolationReason: 'NONE',
          instanceHealthState: 'HEALTHY',
          quarantineReason: 'NONE',
        },
        {
          stage: 'INSTANCE_HEALTH',
          resourceKey: 'cache:redis:user-profile:get',
          action: 'QUARANTINE_CANDIDATE',
          outcome: 'NONE',
          durationBucket: 'NOT_RUN',
          timestamp: '2026-06-24T01:28:19Z',
          rejectionReason: 'NONE',
          blockReason: 'NONE',
          cancellationReason: 'NONE',
          retryStopReason: 'NONE',
          isolationReason: 'NONE',
          instanceHealthState: 'QUARANTINE_CANDIDATE',
          quarantineReason: 'SERVER_ERROR_RATIO',
        },
      ],
    },
    {
      traceKey: 'trace-3',
      rootResourceKey: 'messaging:kafka:orders:send',
      startedAt: '2026-06-24T01:28:17Z',
      lastEventAt: '2026-06-24T01:28:17Z',
      terminalOutcome: 'REJECTED',
      primaryStopReason: 'BLOCKED',
      suggestedResourceKey: 'messaging:kafka:orders:send',
      steps: [
        {
          stage: 'GOVERNANCE',
          resourceKey: 'messaging:kafka:orders:send',
          action: 'REJECT',
          outcome: 'REJECTED',
          durationBucket: 'NOT_RUN',
          timestamp: '2026-06-24T01:28:17Z',
          rejectionReason: 'CIRCUIT_OPEN',
          blockReason: 'CIRCUIT_OPEN',
          cancellationReason: 'NONE',
          retryStopReason: 'CIRCUIT_OPEN',
          isolationReason: 'PRIORITY_CIRCUIT_OPEN',
          instanceHealthState: 'HEALTHY',
          quarantineReason: 'NONE',
        },
      ],
    },
    {
      traceKey: 'trace-2',
      rootResourceKey: 'governance:nexary:default:execute',
      startedAt: '2026-06-24T01:25:19Z',
      lastEventAt: '2026-06-24T01:25:19Z',
      terminalOutcome: 'ISOLATED',
      primaryStopReason: 'ISOLATED',
      suggestedResourceKey: 'governance:nexary:default:execute',
      steps: [
        {
          stage: 'GOVERNANCE',
          resourceKey: 'governance:nexary:default:execute',
          action: 'FALLBACK',
          outcome: 'ISOLATED',
          durationBucket: 'NOT_RUN',
          timestamp: '2026-06-24T01:25:19Z',
          rejectionReason: 'DEGRADED',
          blockReason: 'NONE',
          cancellationReason: 'NONE',
          retryStopReason: 'DEGRADED',
          isolationReason: 'PRIORITY_DEGRADED',
          instanceHealthState: 'HEALTHY',
          quarantineReason: 'NONE',
        },
      ],
    },
    {
      traceKey: 'trace-1',
      rootResourceKey: 'cache:redis:user-profile:get',
      startedAt: '2026-06-24T01:28:12Z',
      lastEventAt: '2026-06-24T01:28:12Z',
      terminalOutcome: 'SUCCESS',
      primaryStopReason: 'NONE',
      suggestedResourceKey: null,
      steps: [
        {
          stage: 'CACHE',
          resourceKey: 'cache:redis:user-profile:get',
          action: 'EXECUTE',
          outcome: 'SUCCESS',
          durationBucket: 'LT_10_MS',
          timestamp: '2026-06-24T01:28:12Z',
          rejectionReason: 'NONE',
          blockReason: 'NONE',
          cancellationReason: 'NONE',
          retryStopReason: 'NONE',
          isolationReason: 'NONE',
          instanceHealthState: 'HEALTHY',
          quarantineReason: 'NONE',
        },
      ],
    },
  ],
  faultTraceSummary: {
    traceCount: 4,
    stoppedCount: 3,
    blockedCount: 1,
    cancelledCount: 0,
    retryStoppedCount: 0,
    instanceRelatedCount: 1,
    topStopReasons: {
      INSTANCE_QUARANTINE_CANDIDATE: 1,
      BLOCKED: 1,
      ISOLATED: 1,
    },
  },
  settings: {
    apiBase: '/nexary/console/api',
    dataMode: 'auto',
    readonly: true,
    refreshIntervalMs: 15000,
    endpointPaths: {
      summary: '/summary',
      resources: '/resources',
      resourceDetail: '/resources/{resourceKey}',
      events: '/events',
      traces: '/traces',
      traceDetail: '/traces/{traceKey}',
      faultSummary: '/faults/summary',
    },
  },
};
