import type { ConsoleDataSet } from '../types/console';

export const mockConsoleData: ConsoleDataSet = {
  summary: {
    resourceCount: 6,
    snapshotCount: 5,
    eventCount: 8,
    successCount: 1842,
    failureCount: 17,
    rejectedCount: 36,
    cancelledCount: 4,
    fallbackCount: 9,
    openCircuitCount: 1,
    halfOpenCircuitCount: 1,
    degradedResourceCount: 1,
    lastEventAt: '2026-06-24T01:28:12Z',
  },
  resources: [
    {
      resourceKey: 'cache:redis:user-profile:get',
      kind: 'CACHE',
      name: 'user-profile',
      provider: 'redis',
      operation: 'get',
      priority: 'normal',
      policySnapshot: {
        maxRequestsPerWindow: 500,
        rateLimitWindow: 'PT1S',
        maxConcurrency: 64,
        degraded: false,
        minimumRequests: 20,
        failureRateThreshold: 50,
        slowCallThreshold: 60,
        slowCallDuration: 'PT0.2S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 2,
        slidingWindowSize: 100,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 8,
      },
      runtimeSnapshot: {
        resourceKey: 'cache:redis:user-profile:get',
        priority: 'normal',
        circuitState: 'CLOSED',
        windowCalls: 96,
        windowFailures: 1,
        windowSlowCalls: 3,
        consecutiveFailures: 0,
        totalRejections: 2,
        lastRejectionReason: 'NONE',
        lastCancellationReason: 'NONE',
        openUntil: null,
        activeConcurrency: 3,
        maxConcurrency: 64,
        maxRequestsPerWindow: 500,
        rateLimitWindow: 'PT1S',
        degraded: false,
        minimumRequests: 20,
        failureRateThreshold: 50,
        slowCallThreshold: 60,
        slowCallDuration: 'PT0.2S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 2,
        slidingWindowSize: 100,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 8,
        lastStateTransitionAt: '2026-06-24T01:20:02Z',
        lastOutcome: 'SUCCESS',
        lastOutcomeAt: '2026-06-24T01:28:12Z',
      },
    },
    {
      resourceKey: 'messaging:kafka:orders:send',
      kind: 'MESSAGING',
      name: 'orders',
      provider: 'kafka',
      operation: 'send',
      priority: 'normal',
      policySnapshot: {
        maxRequestsPerWindow: 120,
        rateLimitWindow: 'PT1S',
        maxConcurrency: 24,
        degraded: false,
        minimumRequests: 12,
        failureRateThreshold: 40,
        slowCallThreshold: 50,
        slowCallDuration: 'PT1S',
        openStateDuration: 'PT45S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 80,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 4,
      },
      runtimeSnapshot: {
        resourceKey: 'messaging:kafka:orders:send',
        priority: 'normal',
        circuitState: 'OPEN',
        windowCalls: 32,
        windowFailures: 15,
        windowSlowCalls: 11,
        consecutiveFailures: 5,
        totalRejections: 28,
        lastRejectionReason: 'CIRCUIT_OPEN',
        lastCancellationReason: 'CLIENT_DISCONNECTED',
        openUntil: '2026-06-24T01:29:00Z',
        activeConcurrency: 0,
        maxConcurrency: 24,
        maxRequestsPerWindow: 120,
        rateLimitWindow: 'PT1S',
        degraded: false,
        minimumRequests: 12,
        failureRateThreshold: 40,
        slowCallThreshold: 50,
        slowCallDuration: 'PT1S',
        openStateDuration: 'PT45S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 80,
        slidingWindowDuration: 'PT60S',
        consecutiveFailureThreshold: 4,
        lastStateTransitionAt: '2026-06-24T01:28:15Z',
        lastOutcome: 'REJECTED',
        lastOutcomeAt: '2026-06-24T01:28:17Z',
      },
    },
    {
      resourceKey: 'job:scheduler:billing-close:run',
      kind: 'JOB',
      name: 'billing-close',
      provider: 'scheduler',
      operation: 'run',
      priority: 'high',
      policySnapshot: {
        maxRequestsPerWindow: 8,
        rateLimitWindow: 'PT1M',
        maxConcurrency: 1,
        degraded: false,
        minimumRequests: 5,
        failureRateThreshold: 50,
        slowCallThreshold: null,
        slowCallDuration: null,
        openStateDuration: 'PT60S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 20,
        slidingWindowDuration: 'PT5M',
        consecutiveFailureThreshold: 3,
      },
      runtimeSnapshot: {
        resourceKey: 'job:scheduler:billing-close:run',
        priority: 'high',
        circuitState: 'HALF_OPEN',
        windowCalls: 9,
        windowFailures: 3,
        windowSlowCalls: 0,
        consecutiveFailures: 0,
        totalRejections: 4,
        lastRejectionReason: 'HALF_OPEN_LIMITED',
        lastCancellationReason: 'NONE',
        openUntil: null,
        activeConcurrency: 1,
        maxConcurrency: 1,
        maxRequestsPerWindow: 8,
        rateLimitWindow: 'PT1M',
        degraded: false,
        minimumRequests: 5,
        failureRateThreshold: 50,
        slowCallThreshold: null,
        slowCallDuration: null,
        openStateDuration: 'PT60S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 20,
        slidingWindowDuration: 'PT5M',
        consecutiveFailureThreshold: 3,
        lastStateTransitionAt: '2026-06-24T01:27:30Z',
        lastOutcome: 'SUCCESS',
        lastOutcomeAt: '2026-06-24T01:28:01Z',
      },
    },
    {
      resourceKey: 'governance:nexary:default:execute',
      kind: 'GOVERNANCE',
      name: 'default',
      provider: 'nexary',
      operation: 'execute',
      priority: 'normal',
      policySnapshot: {
        maxRequestsPerWindow: 200,
        rateLimitWindow: 'PT1S',
        maxConcurrency: 32,
        degraded: true,
        minimumRequests: 10,
        failureRateThreshold: 50,
        slowCallThreshold: 50,
        slowCallDuration: 'PT0.5S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 50,
        slidingWindowDuration: 'PT30S',
        consecutiveFailureThreshold: 5,
      },
      runtimeSnapshot: {
        resourceKey: 'governance:nexary:default:execute',
        priority: 'normal',
        circuitState: 'CLOSED',
        windowCalls: 20,
        windowFailures: 0,
        windowSlowCalls: 0,
        consecutiveFailures: 0,
        totalRejections: 2,
        lastRejectionReason: 'DEGRADED',
        lastCancellationReason: 'NONE',
        openUntil: null,
        activeConcurrency: 0,
        maxConcurrency: 32,
        maxRequestsPerWindow: 200,
        rateLimitWindow: 'PT1S',
        degraded: true,
        minimumRequests: 10,
        failureRateThreshold: 50,
        slowCallThreshold: 50,
        slowCallDuration: 'PT0.5S',
        openStateDuration: 'PT30S',
        halfOpenMaxCalls: 1,
        slidingWindowSize: 50,
        slidingWindowDuration: 'PT30S',
        consecutiveFailureThreshold: 5,
        lastStateTransitionAt: '2026-06-24T01:10:00Z',
        lastOutcome: 'REJECTED',
        lastOutcomeAt: '2026-06-24T01:25:19Z',
      },
    },
  ],
  events: [
    {
      resourceKey: 'messaging:kafka:orders:send',
      action: 'REJECT',
      outcome: 'REJECTED',
      rejectionReason: 'CIRCUIT_OPEN',
      cancellationReason: 'NONE',
      circuitState: 'OPEN',
      timestamp: '2026-06-24T01:28:17Z',
      durationBucket: 'NOT_RUN',
    },
    {
      resourceKey: 'cache:redis:user-profile:get',
      action: 'EXECUTE',
      outcome: 'SUCCESS',
      rejectionReason: 'NONE',
      cancellationReason: 'NONE',
      circuitState: 'CLOSED',
      timestamp: '2026-06-24T01:28:12Z',
      durationBucket: 'FAST',
    },
    {
      resourceKey: 'job:scheduler:billing-close:run',
      action: 'EXECUTE',
      outcome: 'SUCCESS',
      rejectionReason: 'NONE',
      cancellationReason: 'NONE',
      circuitState: 'HALF_OPEN',
      timestamp: '2026-06-24T01:28:01Z',
      durationBucket: 'NORMAL',
    },
    {
      resourceKey: 'governance:nexary:default:execute',
      action: 'FALLBACK',
      outcome: 'REJECTED',
      rejectionReason: 'DEGRADED',
      cancellationReason: 'NONE',
      circuitState: 'CLOSED',
      timestamp: '2026-06-24T01:25:19Z',
      durationBucket: 'NOT_RUN',
    },
    {
      resourceKey: 'messaging:kafka:orders:send',
      action: 'CANCEL',
      outcome: 'CANCELLED',
      rejectionReason: 'NONE',
      cancellationReason: 'CLIENT_DISCONNECTED',
      circuitState: 'OPEN',
      timestamp: '2026-06-24T01:25:10Z',
      durationBucket: 'NOT_RUN',
    },
  ],
  settings: {
    apiBase: '/nexary/console/api',
    dataMode: 'auto',
    readonly: true,
    refreshIntervalMs: 15000,
    endpointPaths: {
      summary: '/summary',
      resources: '/resources',
      resourceDetail: '/resources/{resourceKey}',
      events: '/events',
    },
  },
};
